import "@/styles/global.css";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import { cn } from "@/src/lib/utils";
import { ToastProvider } from "../context/toast-context";
import { WishlistProvider } from "../context/wishList-context";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const vazir_m = localFont({
  src: "../../public/font/Vazir-Regular.woff2",
  variable: "--font-vazir",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      className={cn(
        "antialiased",
        vazir_m.variable,
        "font-sans",
        inter.variable,
      )}
      lang="fa"
      dir="rtl"
    >
      <body>
        <ToastProvider>{children}</ToastProvider>

        <div id="toast-root"></div>
      </body>
    </html>
  );
}
